"use client";

import { useMemo, useState } from "react";
import type { BalanceSheet, Player } from "@/lib/soccerverse";
import { formatSVC } from "@/lib/soccerverse";

export function SquadWorkspace({ squad }: { squad: Player[] }) {
  const [filter, setFilter] = useState("all");
  const filtered = useMemo(() => squad.filter((player) => filter === "all" || (filter === "injured" && Boolean(player.injured)) || (filter === "contract" && player.contract > 0) || (filter === "transfer" && Boolean(player.allow_transfer)) || (filter === "loans" && Boolean(player.loaned_to_club))), [filter, squad]);
  const totalWages = squad.reduce((total, player) => total + player.wages, 0);
  const average = (key: (player: Player) => number) => squad.length ? squad.reduce((total, player) => total + key(player), 0) / squad.length : 0;
  const filters = [["all", `All (${squad.length})`], ["injured", `Injured (${squad.filter((player) => player.injured).length})`], ["contract", `Contract (${squad.filter((player) => player.contract > 0).length})`], ["transfer", "Transfer listed"], ["loans", "Loans"]];
  return <section className="club-workspace squad-workspace"><div className="workspace-stats"><Metric label="PLAYERS" value={String(squad.length)}/><Metric label="AVG RATING" value={average((player) => player.rating).toFixed(1)} tone="green"/><Metric label="AVG AGE" value={average((player) => player.age).toFixed(1)}/><Metric label="SQUAD WAGE" value={`${formatSVC(totalWages)}/wk`}/><Metric label="AVG WAGE" value={`${formatSVC(Math.round(totalWages / Math.max(1, squad.length)))}/wk`}/><Metric label="TOTAL WAGES" value={`${formatSVC(totalWages * 39)}/season`}/></div><div className="workspace-toolbar">{filters.map(([id, label]) => <button className={filter === id ? "active" : ""} onClick={() => setFilter(id)} key={id}>{label}</button>)}</div><div className="rule-note">ℹ Clubs must have a minimum of 21 players and a maximum of 32 players.</div><div className="squad-table"><header><span>POS</span><span>PLAYER</span><span>RTG</span><span>AGE</span><span>FITNESS</span><span>FORM</span><span>WAGES</span><span>VALUATION</span><span>CONTRACT</span><span>STATUS</span></header>{filtered.map((player) => <div className="squad-player" key={player.player_id}><span className="position-pill">{player.position_main}</span><span className="player-cell"><img src={`https://elrincondeldt.com/sv/photos/players_webp/${player.player_id}.webp`} alt=""/><b>{player.display_name}</b><small>{player.country_id}</small></span><span className="rating-box">{player.rating}</span><span>{player.age}</span><span className={player.fitness < 80 ? "fitness warn" : "fitness"}>{player.fitness}%</span><span className="form-dots">{player.form.replace(/-/g, "·") || "—"}</span><span>{formatSVC(player.wages)}/wk</span><span>{formatSVC(player.value)}</span><span>{player.contract ? `${player.contract}s` : "—"}</span><span>{player.injured ? "INJ" : player.banned ? "BAN" : "—"}</span></div>)}</div></section>;
}

export function FinanceWorkspace({ balanceSheet, balance }: { balanceSheet: BalanceSheet[]; balance: number }) {
  const entries = [...balanceSheet].sort((left, right) => left.date - right.date).slice(-6);
  const income = (entry: BalanceSheet) => entry.cash_injection + entry.gate_receipts + entry.tv_revenue + entry.sponsor + entry.merchandise + entry.transfers_out + entry.prize_money + entry.other_income;
  const expenses = (entry: BalanceSheet) => entry.player_wages + entry.ground_maintenance + entry.managers_wage + entry.agent_wages + entry.shareholder_payouts + entry.transfers_in + entry.other_outgoings;
  const totalIncome = entries.reduce((total, entry) => total + income(entry), 0); const totalExpenses = entries.reduce((total, entry) => total + expenses(entry), 0);
  const rows: Array<[string, keyof BalanceSheet, "income" | "expense"]> = [["Cash Injection", "cash_injection", "income"], ["Gate Receipts", "gate_receipts", "income"], ["TV Revenue", "tv_revenue", "income"], ["Sponsors", "sponsor", "income"], ["Merchandise", "merchandise", "income"], ["Transfers Out", "transfers_out", "income"], ["Prize Money", "prize_money", "income"], ["Transfers In", "transfers_in", "expense"], ["Player Wages", "player_wages", "expense"], ["Ground Maintenance", "ground_maintenance", "expense"], ["Manager's Wage", "managers_wage", "expense"], ["Influencer Payouts", "shareholder_payouts", "expense"]];
  return <section className="club-workspace finance-workspace"><header className="finance-title"><b>BALANCE SHEET</b><span>Season 4 · latest {entries.length} game weeks</span></header><div className="balance-table"><header><span>ITEM</span>{entries.map((entry) => <span key={entry.balance_sheet_id}>{new Intl.DateTimeFormat("en", { day: "numeric", month: "short" }).format(new Date(entry.date * 1000))}</span>)}</header><div className="balance-section income">INCOME</div>{rows.filter(([, , type]) => type === "income").map(([label, key]) => <BalanceRow key={label} label={label} entries={entries} value={(entry) => entry[key] as number} tone="income"/>)}<BalanceRow label="TOTAL INCOME" entries={entries} value={income} tone="income" strong/><div className="balance-section expense">EXPENSES</div>{rows.filter(([, , type]) => type === "expense").map(([label, key]) => <BalanceRow key={label} label={label} entries={entries} value={(entry) => entry[key] as number} tone="expense"/>)}<BalanceRow label="TOTAL EXPENSES" entries={entries} value={expenses} tone="expense" strong/><BalanceRow label="NET INCOME" entries={entries} value={(entry) => income(entry) - expenses(entry)} tone="net" strong/></div><div className="finance-summary"><article><h3>SUMMARY</h3><p>Season income <b className="positive">{formatSVC(totalIncome)}</b></p><p>Season expenses <b className="negative">{formatSVC(totalExpenses)}</b></p><p>Current balance <b className="positive">{formatSVC(balance)}</b></p></article><article className="cashflow"><h3>CASH FLOW</h3>{entries.map((entry) => { const net = income(entry) - expenses(entry); return <div key={entry.balance_sheet_id}><span>{entry.game_week ? `GW ${entry.game_week}` : "Week"}</span><i style={{ width: `${Math.min(100, Math.abs(net) / Math.max(1, ...entries.map((item) => Math.abs(income(item) - expenses(item)))) * 100)}%` }} className={net >= 0 ? "positive-bar" : "negative-bar"}/><b className={net >= 0 ? "positive" : "negative"}>{formatSVC(net)}</b></div>; })}</article></div></section>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div><small>{label}</small><b className={tone}>{value}</b></div>; }
function BalanceRow({ label, entries, value, tone, strong = false }: { label: string; entries: BalanceSheet[]; value: (entry: BalanceSheet) => number; tone: string; strong?: boolean }) { return <div className={`balance-row ${tone} ${strong ? "strong" : ""}`}><span>{label}</span>{entries.map((entry) => { const amount = value(entry); return <span key={entry.balance_sheet_id}>{amount ? formatSVC(amount) : "–"}</span>; })}</div>; }
